### ISSUE TITLE
History of Games?

### ISSUE THREAD

**Issue by skylar01** [zero-to-mastery/worldcup-2018#14]
Maybe we can do something like a history page for all of the past games?

**Comment by kudeh** [comment]
That would be a Results page. I'm thinking fixtures and results can be on the same page though. So if the match has been played show the scores else show the date and time of the match.

**Comment by ursrudra** [comment]
@skylar01 okay, we can include it in Teams Page, i will update it today

**Comment by MattCSmith** [comment]
I was going to close this as it appears to have been implemented, However we could always take this a step further and separate the played matches from the to be played matches. Maybe this could be done in the form of a filter or toggle.

**Comment by skylar01** [comment]
We should agree with how we would do it, other's would want to put it in fixtures other's including me want it to be separated.

**Comment by MattCSmith** [comment]
Closing due to project completion
