### ISSUE TITLE
Fix the HomePage layout

### ISSUE THREAD

**Issue by djohal** [zero-to-mastery/worldcup-2018#15]
Seems like the recent stlye updates broke the HomePage layout. The last time it was working was in commit `fc222a9a70616a1b294e0054e7389a389e914f49`, should look like this:

![image](https://user-images.githubusercontent.com/9207593/41192225-bd8cd5b2-6bc8-11e8-8965-82d72d95a90f.png)

**Comment by lexantus** [comment]
I am fixing it now

**Comment by lexantus** [comment]
https://github.com/zero-to-mastery/worldcup-2018/pull/16

**Comment by djohal** [comment]
@lexantus  Thanks for fixing it! Closing this issue.
