### ISSUE TITLE
Stadium Map Feature

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/worldcup-2018#3]
Add a map with stadium pins
https://hackernoon.com/implement-google-maps-in-reactjs-5bc218074689

**Comment by lexantus** [comment]
I can help with this feature. I've already connected googlemap.

**Comment by MattCSmith** [comment]
Closing due to core feature being implemented here:  https://github.com/zero-to-mastery/worldcup-2018/pull/7

Feel free to reopen, if you have further suggestions!
