### ISSUE TITLE
About Discord?

### ISSUE THREAD

**Issue by skylar01** [zero-to-mastery/worldcup-2018#31]
Hey guys, just gonna ask. why did we even put our discord in the contributors.md am I missing something? i'm still not in the discord if there's any... sorry I have to put this on issues as I do not know where should I ask.

**Comment by MattCSmith** [comment]
Hey @skylar01,
We thought that having discord details next to your name, would be helpful incase someone needed to chat to you about any of your PRs.

Ztm has a community discord group, with over 7k members where you can gain help or generally chat with other people learning the course. I would definitely recommend joining it.

You should be able to find the information in one of the earlier videos of Andrei's course.
Regards 
Matt

**Comment by MattCSmith** [comment]
Section 1 - Part 3
Join Our Online Classroom!

You should be able to find the link and information there

**Comment by skylar01** [comment]
oh okay Thank you @MattCSmith I overlooked it.
