### ISSUE TITLE
Scores and Date Feature

### ISSUE THREAD

**Issue by djohal** [zero-to-mastery/worldcup-2018#4]
Add scores and date feature in fixtures. Should look something like this: 

![image](https://user-images.githubusercontent.com/9207593/41102410-d5bf31a6-6a34-11e8-91ba-b80bf065ae8b.png)

**Comment by kudeh** [comment]
Just did a PR with this feature to show fixtures. Results can be added later by using a conditional statement.

**Comment by djohal** [comment]
Closing this as the feature is implemented now.
