### ISSUE TITLE
On gh-pages branch when open index.html there are errors in console

### ISSUE THREAD

**Issue by lexantus** [zero-to-mastery/worldcup-2018#41]
![screen shot 2018-06-13 at 22 23 42](https://user-images.githubusercontent.com/4254203/41373256-7e56ba6e-6f58-11e8-9709-9e3e27f06355.png)

**Comment by lexantus** [comment]
I try to figure out why this errors occured. But without success. Please, help me

**Comment by MattCSmith** [comment]
Closing this as it appears to have been fixed, feel free to re-open if that is not the case
