### ISSUE TITLE
Statistics data updating

### ISSUE THREAD

**Issue by elir92** [zero-to-mastery/worldcup-2018#45]
Hey,
I created an external js files for the statistic data. for top scorer and for top assists.
I didn't find an API for this data, so i guess we should manually update them for now.
I also think there will be more parameters like cards, corners maybe, etc..  so welcome to add.
For now i will delete the hard-coded data so after the first game anyone can update the data (in the external files)

**Comment by kudeh** [comment]
Just combined the assists and scorers js files into one that records players by team. Should help make it more maintainable and reduce the chance of inputting duplicate player info. So anyone updating those stats should goto the team_players.js file.

**Comment by elir92** [comment]
Much more cleaner. great!

**Comment by MattCSmith** [comment]
closing due to project completion
